# Generated by Django 2.2.14 on 2022-05-21 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addressTable',
            fields=[
                ('address_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('user_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('user_type', models.PositiveSmallIntegerField(choices=[(1, 'user'), (2, 'vendor'), (3, 'admin')], default=1)),
                ('verified', models.PositiveSmallIntegerField(choices=[(1, 'verified'), (2, 'not-verified')], default=2)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('profile_pic', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='verificationTable',
            fields=[
                ('verification_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_of_doc', models.CharField(max_length=200)),
                ('document_url', models.CharField(max_length=200)),
                ('verified', models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'DONE')], default=1)),
                ('uploaded_date', models.DateTimeField()),
                ('verified_date', models.DateTimeField()),
                ('vendor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='psqldb.UserTable')),
                ('verified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='psqldb.UserTable')),
            ],
        ),
        migrations.CreateModel(
            name='ProductTable',
            fields=[
                ('product_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('image', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psqldb.UserTable')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTable',
            fields=[
                ('payment_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILED')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psqldb.UserTable')),
            ],
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('order_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('delivered', models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'DONE')], default=1)),
                ('shipped', models.PositiveSmallIntegerField(choices=[(1, 'PENDING'), (2, 'DONE')], default=1)),
                ('payment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psqldb.PaymentTable')),
                ('shipping_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psqldb.addressTable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psqldb.UserTable')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemTable',
            fields=[
                ('order_item_uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qty', models.CharField(max_length=200)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psqldb.OrderTable')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psqldb.ProductTable')),
            ],
        ),
        migrations.AddField(
            model_name='addresstable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='psqldb.UserTable'),
        ),
    ]
