# Generated by Django 2.2.14 on 2022-05-24 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psqldb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitemtable',
            name='custom_image',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='orderitemtable',
            name='custom_text',
            field=models.CharField(default=0, max_length=200),
        ),
        migrations.AddField(
            model_name='producttable',
            name='customizable',
            field=models.PositiveSmallIntegerField(choices=[(1, True), (2, False)], default=2),
        ),
    ]
